<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Practical Machine Learning</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h2>Practical Machine Learning</h2>

<h2>Course Project by Nils Eicke</h2>

<p>In this project, the goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants.
They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website 
here: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a> (see the section on the Weight Lifting Exercise Dataset). 
For this project training data and test data were used. The data for this project come from this source: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a>.</p>

<p>The goal of this project is to predict the manner in which the participants did the exercise. This is the &ldquo;classe&rdquo; variable in the 
training set. Almost any of the other variables are used to predict with. It is described how the model has been built, how 
cross validation has been used, what I think the expected out of sample error is, and why I made the choices I did. 
The prediction model has been also used to predict 20 different test cases. </p>

<p>Firstly packages and data has been loaded into R </p>

<pre><code class="r">#load packages
install.packages(&quot;AppliedPredictiveModeling&quot;)
</code></pre>

<pre><code>## Warning: package &#39;AppliedPredictiveModeling&#39; is in use and will not be
## installed
</code></pre>

<pre><code class="r">install.packages(&quot;caret&quot;)
</code></pre>

<pre><code>## Warning: package &#39;caret&#39; is in use and will not be installed
</code></pre>

<pre><code class="r">install.packages(&quot;randomForest&quot;)
</code></pre>

<pre><code>## Warning: package &#39;randomForest&#39; is in use and will not be installed
</code></pre>

<pre><code class="r">install.packages(&quot;e1071&quot;)
</code></pre>

<pre><code>## Warning: package &#39;e1071&#39; is in use and will not be installed
</code></pre>

<pre><code class="r">library(AppliedPredictiveModeling)
library(caret)
library(e1071)
library(randomForest)

#download training data
download.file(url=&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv&quot;, destfile=&quot;data/pml-training.csv&quot;)

#download test data
download.file(url=&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv&quot;, destfile=&quot;data/pml-testing.csv&quot;)

#import data; set empty values to NA
training_set &lt;- read.csv(&quot;data/pml-training.csv&quot;, na.strings=c(&quot;NA&quot;,&quot;&quot;), header=TRUE)
testing_set &lt;- read.csv(&quot;data/pml-testing.csv&quot;, na.strings=c(&quot;NA&quot;,&quot;&quot;), header=TRUE)
</code></pre>

<p>Secondly data has been explored.</p>

<pre><code class="r">dim(training_set)
</code></pre>

<pre><code>## [1] 19622   160
</code></pre>

<pre><code class="r">dim(testing_set)
</code></pre>

<pre><code>## [1]  20 160
</code></pre>

<pre><code class="r">countNAs &lt;- function(x) {
    #create count NAs vector
    countNA &lt;- names(x)
    countNA &lt;- rbind(countNA,0)

    #determine number of NAs for each column
    for (i in 1:length(names(x))) {
        countNA[2,i] &lt;- length(which(is.na(x[,i])))
    }
    print(countNA)
}

test_countNAs &lt;- countNAs(testing_set)
</code></pre>

<pre><code>##         [,1] [,2]        [,3]                   [,4]                  
## countNA &quot;X&quot;  &quot;user_name&quot; &quot;raw_timestamp_part_1&quot; &quot;raw_timestamp_part_2&quot;
##         &quot;0&quot;  &quot;0&quot;         &quot;0&quot;                    &quot;0&quot;                   
##         [,5]             [,6]         [,7]         [,8]       
## countNA &quot;cvtd_timestamp&quot; &quot;new_window&quot; &quot;num_window&quot; &quot;roll_belt&quot;
##         &quot;0&quot;              &quot;0&quot;          &quot;0&quot;          &quot;0&quot;        
##         [,9]         [,10]      [,11]              [,12]               
## countNA &quot;pitch_belt&quot; &quot;yaw_belt&quot; &quot;total_accel_belt&quot; &quot;kurtosis_roll_belt&quot;
##         &quot;0&quot;          &quot;0&quot;        &quot;0&quot;                &quot;20&quot;                
##         [,13]                 [,14]               [,15]               
## countNA &quot;kurtosis_picth_belt&quot; &quot;kurtosis_yaw_belt&quot; &quot;skewness_roll_belt&quot;
##         &quot;20&quot;                  &quot;20&quot;                &quot;20&quot;                
##         [,16]                  [,17]               [,18]          
## countNA &quot;skewness_roll_belt.1&quot; &quot;skewness_yaw_belt&quot; &quot;max_roll_belt&quot;
##         &quot;20&quot;                   &quot;20&quot;                &quot;20&quot;           
##         [,19]            [,20]          [,21]           [,22]           
## countNA &quot;max_picth_belt&quot; &quot;max_yaw_belt&quot; &quot;min_roll_belt&quot; &quot;min_pitch_belt&quot;
##         &quot;20&quot;             &quot;20&quot;           &quot;20&quot;            &quot;20&quot;            
##         [,23]          [,24]                 [,25]                 
## countNA &quot;min_yaw_belt&quot; &quot;amplitude_roll_belt&quot; &quot;amplitude_pitch_belt&quot;
##         &quot;20&quot;           &quot;20&quot;                  &quot;20&quot;                  
##         [,26]                [,27]                  [,28]          
## countNA &quot;amplitude_yaw_belt&quot; &quot;var_total_accel_belt&quot; &quot;avg_roll_belt&quot;
##         &quot;20&quot;                 &quot;20&quot;                   &quot;20&quot;           
##         [,29]              [,30]           [,31]           
## countNA &quot;stddev_roll_belt&quot; &quot;var_roll_belt&quot; &quot;avg_pitch_belt&quot;
##         &quot;20&quot;               &quot;20&quot;            &quot;20&quot;            
##         [,32]               [,33]            [,34]         
## countNA &quot;stddev_pitch_belt&quot; &quot;var_pitch_belt&quot; &quot;avg_yaw_belt&quot;
##         &quot;20&quot;                &quot;20&quot;             &quot;20&quot;          
##         [,35]             [,36]          [,37]          [,38]         
## countNA &quot;stddev_yaw_belt&quot; &quot;var_yaw_belt&quot; &quot;gyros_belt_x&quot; &quot;gyros_belt_y&quot;
##         &quot;20&quot;              &quot;20&quot;           &quot;0&quot;            &quot;0&quot;           
##         [,39]          [,40]          [,41]          [,42]         
## countNA &quot;gyros_belt_z&quot; &quot;accel_belt_x&quot; &quot;accel_belt_y&quot; &quot;accel_belt_z&quot;
##         &quot;0&quot;            &quot;0&quot;            &quot;0&quot;            &quot;0&quot;           
##         [,43]           [,44]           [,45]           [,46]     
## countNA &quot;magnet_belt_x&quot; &quot;magnet_belt_y&quot; &quot;magnet_belt_z&quot; &quot;roll_arm&quot;
##         &quot;0&quot;             &quot;0&quot;             &quot;0&quot;             &quot;0&quot;       
##         [,47]       [,48]     [,49]             [,50]          
## countNA &quot;pitch_arm&quot; &quot;yaw_arm&quot; &quot;total_accel_arm&quot; &quot;var_accel_arm&quot;
##         &quot;0&quot;         &quot;0&quot;       &quot;0&quot;               &quot;20&quot;           
##         [,51]          [,52]             [,53]          [,54]          
## countNA &quot;avg_roll_arm&quot; &quot;stddev_roll_arm&quot; &quot;var_roll_arm&quot; &quot;avg_pitch_arm&quot;
##         &quot;20&quot;           &quot;20&quot;              &quot;20&quot;           &quot;20&quot;           
##         [,55]              [,56]           [,57]         [,58]           
## countNA &quot;stddev_pitch_arm&quot; &quot;var_pitch_arm&quot; &quot;avg_yaw_arm&quot; &quot;stddev_yaw_arm&quot;
##         &quot;20&quot;               &quot;20&quot;            &quot;20&quot;          &quot;20&quot;            
##         [,59]         [,60]         [,61]         [,62]        
## countNA &quot;var_yaw_arm&quot; &quot;gyros_arm_x&quot; &quot;gyros_arm_y&quot; &quot;gyros_arm_z&quot;
##         &quot;20&quot;          &quot;0&quot;           &quot;0&quot;           &quot;0&quot;          
##         [,63]         [,64]         [,65]         [,66]         
## countNA &quot;accel_arm_x&quot; &quot;accel_arm_y&quot; &quot;accel_arm_z&quot; &quot;magnet_arm_x&quot;
##         &quot;0&quot;           &quot;0&quot;           &quot;0&quot;           &quot;0&quot;           
##         [,67]          [,68]          [,69]              
## countNA &quot;magnet_arm_y&quot; &quot;magnet_arm_z&quot; &quot;kurtosis_roll_arm&quot;
##         &quot;0&quot;            &quot;0&quot;            &quot;20&quot;               
##         [,70]                [,71]              [,72]              
## countNA &quot;kurtosis_picth_arm&quot; &quot;kurtosis_yaw_arm&quot; &quot;skewness_roll_arm&quot;
##         &quot;20&quot;                 &quot;20&quot;               &quot;20&quot;               
##         [,73]                [,74]              [,75]         
## countNA &quot;skewness_pitch_arm&quot; &quot;skewness_yaw_arm&quot; &quot;max_roll_arm&quot;
##         &quot;20&quot;                 &quot;20&quot;               &quot;20&quot;          
##         [,76]           [,77]         [,78]          [,79]          
## countNA &quot;max_picth_arm&quot; &quot;max_yaw_arm&quot; &quot;min_roll_arm&quot; &quot;min_pitch_arm&quot;
##         &quot;20&quot;            &quot;20&quot;          &quot;20&quot;           &quot;20&quot;           
##         [,80]         [,81]                [,82]                
## countNA &quot;min_yaw_arm&quot; &quot;amplitude_roll_arm&quot; &quot;amplitude_pitch_arm&quot;
##         &quot;20&quot;          &quot;20&quot;                 &quot;20&quot;                 
##         [,83]               [,84]           [,85]           
## countNA &quot;amplitude_yaw_arm&quot; &quot;roll_dumbbell&quot; &quot;pitch_dumbbell&quot;
##         &quot;20&quot;                &quot;0&quot;             &quot;0&quot;             
##         [,86]          [,87]                    [,88]                    
## countNA &quot;yaw_dumbbell&quot; &quot;kurtosis_roll_dumbbell&quot; &quot;kurtosis_picth_dumbbell&quot;
##         &quot;0&quot;            &quot;20&quot;                     &quot;20&quot;                     
##         [,89]                   [,90]                   
## countNA &quot;kurtosis_yaw_dumbbell&quot; &quot;skewness_roll_dumbbell&quot;
##         &quot;20&quot;                    &quot;20&quot;                    
##         [,91]                     [,92]                  
## countNA &quot;skewness_pitch_dumbbell&quot; &quot;skewness_yaw_dumbbell&quot;
##         &quot;20&quot;                      &quot;20&quot;                   
##         [,93]               [,94]                [,95]             
## countNA &quot;max_roll_dumbbell&quot; &quot;max_picth_dumbbell&quot; &quot;max_yaw_dumbbell&quot;
##         &quot;20&quot;                &quot;20&quot;                 &quot;20&quot;              
##         [,96]               [,97]                [,98]             
## countNA &quot;min_roll_dumbbell&quot; &quot;min_pitch_dumbbell&quot; &quot;min_yaw_dumbbell&quot;
##         &quot;20&quot;                &quot;20&quot;                 &quot;20&quot;              
##         [,99]                     [,100]                    
## countNA &quot;amplitude_roll_dumbbell&quot; &quot;amplitude_pitch_dumbbell&quot;
##         &quot;20&quot;                      &quot;20&quot;                      
##         [,101]                   [,102]                
## countNA &quot;amplitude_yaw_dumbbell&quot; &quot;total_accel_dumbbell&quot;
##         &quot;20&quot;                     &quot;0&quot;                   
##         [,103]               [,104]              [,105]                
## countNA &quot;var_accel_dumbbell&quot; &quot;avg_roll_dumbbell&quot; &quot;stddev_roll_dumbbell&quot;
##         &quot;20&quot;                 &quot;20&quot;                &quot;20&quot;                  
##         [,106]              [,107]               [,108]                 
## countNA &quot;var_roll_dumbbell&quot; &quot;avg_pitch_dumbbell&quot; &quot;stddev_pitch_dumbbell&quot;
##         &quot;20&quot;                &quot;20&quot;                 &quot;20&quot;                   
##         [,109]               [,110]             [,111]               
## countNA &quot;var_pitch_dumbbell&quot; &quot;avg_yaw_dumbbell&quot; &quot;stddev_yaw_dumbbell&quot;
##         &quot;20&quot;                 &quot;20&quot;               &quot;20&quot;                 
##         [,112]             [,113]             [,114]            
## countNA &quot;var_yaw_dumbbell&quot; &quot;gyros_dumbbell_x&quot; &quot;gyros_dumbbell_y&quot;
##         &quot;20&quot;               &quot;0&quot;                &quot;0&quot;               
##         [,115]             [,116]             [,117]            
## countNA &quot;gyros_dumbbell_z&quot; &quot;accel_dumbbell_x&quot; &quot;accel_dumbbell_y&quot;
##         &quot;0&quot;                &quot;0&quot;                &quot;0&quot;               
##         [,118]             [,119]              [,120]             
## countNA &quot;accel_dumbbell_z&quot; &quot;magnet_dumbbell_x&quot; &quot;magnet_dumbbell_y&quot;
##         &quot;0&quot;                &quot;0&quot;                 &quot;0&quot;                
##         [,121]              [,122]         [,123]          [,124]       
## countNA &quot;magnet_dumbbell_z&quot; &quot;roll_forearm&quot; &quot;pitch_forearm&quot; &quot;yaw_forearm&quot;
##         &quot;0&quot;                 &quot;0&quot;            &quot;0&quot;             &quot;0&quot;          
##         [,125]                  [,126]                  
## countNA &quot;kurtosis_roll_forearm&quot; &quot;kurtosis_picth_forearm&quot;
##         &quot;20&quot;                    &quot;20&quot;                    
##         [,127]                 [,128]                 
## countNA &quot;kurtosis_yaw_forearm&quot; &quot;skewness_roll_forearm&quot;
##         &quot;20&quot;                   &quot;20&quot;                   
##         [,129]                   [,130]                 [,131]            
## countNA &quot;skewness_pitch_forearm&quot; &quot;skewness_yaw_forearm&quot; &quot;max_roll_forearm&quot;
##         &quot;20&quot;                     &quot;20&quot;                   &quot;20&quot;              
##         [,132]              [,133]            [,134]            
## countNA &quot;max_picth_forearm&quot; &quot;max_yaw_forearm&quot; &quot;min_roll_forearm&quot;
##         &quot;20&quot;                &quot;20&quot;              &quot;20&quot;              
##         [,135]              [,136]            [,137]                  
## countNA &quot;min_pitch_forearm&quot; &quot;min_yaw_forearm&quot; &quot;amplitude_roll_forearm&quot;
##         &quot;20&quot;                &quot;20&quot;              &quot;20&quot;                    
##         [,138]                    [,139]                 
## countNA &quot;amplitude_pitch_forearm&quot; &quot;amplitude_yaw_forearm&quot;
##         &quot;20&quot;                      &quot;20&quot;                   
##         [,140]                [,141]              [,142]            
## countNA &quot;total_accel_forearm&quot; &quot;var_accel_forearm&quot; &quot;avg_roll_forearm&quot;
##         &quot;0&quot;                   &quot;20&quot;                &quot;20&quot;              
##         [,143]                [,144]             [,145]             
## countNA &quot;stddev_roll_forearm&quot; &quot;var_roll_forearm&quot; &quot;avg_pitch_forearm&quot;
##         &quot;20&quot;                  &quot;20&quot;               &quot;20&quot;               
##         [,146]                 [,147]              [,148]           
## countNA &quot;stddev_pitch_forearm&quot; &quot;var_pitch_forearm&quot; &quot;avg_yaw_forearm&quot;
##         &quot;20&quot;                   &quot;20&quot;                &quot;20&quot;             
##         [,149]               [,150]            [,151]           
## countNA &quot;stddev_yaw_forearm&quot; &quot;var_yaw_forearm&quot; &quot;gyros_forearm_x&quot;
##         &quot;20&quot;                 &quot;20&quot;              &quot;0&quot;              
##         [,152]            [,153]            [,154]           
## countNA &quot;gyros_forearm_y&quot; &quot;gyros_forearm_z&quot; &quot;accel_forearm_x&quot;
##         &quot;0&quot;               &quot;0&quot;               &quot;0&quot;              
##         [,155]            [,156]            [,157]            
## countNA &quot;accel_forearm_y&quot; &quot;accel_forearm_z&quot; &quot;magnet_forearm_x&quot;
##         &quot;0&quot;               &quot;0&quot;               &quot;0&quot;               
##         [,158]             [,159]             [,160]      
## countNA &quot;magnet_forearm_y&quot; &quot;magnet_forearm_z&quot; &quot;problem_id&quot;
##         &quot;0&quot;                &quot;0&quot;                &quot;0&quot;
</code></pre>

<pre><code class="r">train_countNAs &lt;- countNAs(training_set)
</code></pre>

<pre><code>##         [,1] [,2]        [,3]                   [,4]                  
## countNA &quot;X&quot;  &quot;user_name&quot; &quot;raw_timestamp_part_1&quot; &quot;raw_timestamp_part_2&quot;
##         &quot;0&quot;  &quot;0&quot;         &quot;0&quot;                    &quot;0&quot;                   
##         [,5]             [,6]         [,7]         [,8]       
## countNA &quot;cvtd_timestamp&quot; &quot;new_window&quot; &quot;num_window&quot; &quot;roll_belt&quot;
##         &quot;0&quot;              &quot;0&quot;          &quot;0&quot;          &quot;0&quot;        
##         [,9]         [,10]      [,11]              [,12]               
## countNA &quot;pitch_belt&quot; &quot;yaw_belt&quot; &quot;total_accel_belt&quot; &quot;kurtosis_roll_belt&quot;
##         &quot;0&quot;          &quot;0&quot;        &quot;0&quot;                &quot;19216&quot;             
##         [,13]                 [,14]               [,15]               
## countNA &quot;kurtosis_picth_belt&quot; &quot;kurtosis_yaw_belt&quot; &quot;skewness_roll_belt&quot;
##         &quot;19216&quot;               &quot;19216&quot;             &quot;19216&quot;             
##         [,16]                  [,17]               [,18]          
## countNA &quot;skewness_roll_belt.1&quot; &quot;skewness_yaw_belt&quot; &quot;max_roll_belt&quot;
##         &quot;19216&quot;                &quot;19216&quot;             &quot;19216&quot;        
##         [,19]            [,20]          [,21]           [,22]           
## countNA &quot;max_picth_belt&quot; &quot;max_yaw_belt&quot; &quot;min_roll_belt&quot; &quot;min_pitch_belt&quot;
##         &quot;19216&quot;          &quot;19216&quot;        &quot;19216&quot;         &quot;19216&quot;         
##         [,23]          [,24]                 [,25]                 
## countNA &quot;min_yaw_belt&quot; &quot;amplitude_roll_belt&quot; &quot;amplitude_pitch_belt&quot;
##         &quot;19216&quot;        &quot;19216&quot;               &quot;19216&quot;               
##         [,26]                [,27]                  [,28]          
## countNA &quot;amplitude_yaw_belt&quot; &quot;var_total_accel_belt&quot; &quot;avg_roll_belt&quot;
##         &quot;19216&quot;              &quot;19216&quot;                &quot;19216&quot;        
##         [,29]              [,30]           [,31]           
## countNA &quot;stddev_roll_belt&quot; &quot;var_roll_belt&quot; &quot;avg_pitch_belt&quot;
##         &quot;19216&quot;            &quot;19216&quot;         &quot;19216&quot;         
##         [,32]               [,33]            [,34]         
## countNA &quot;stddev_pitch_belt&quot; &quot;var_pitch_belt&quot; &quot;avg_yaw_belt&quot;
##         &quot;19216&quot;             &quot;19216&quot;          &quot;19216&quot;       
##         [,35]             [,36]          [,37]          [,38]         
## countNA &quot;stddev_yaw_belt&quot; &quot;var_yaw_belt&quot; &quot;gyros_belt_x&quot; &quot;gyros_belt_y&quot;
##         &quot;19216&quot;           &quot;19216&quot;        &quot;0&quot;            &quot;0&quot;           
##         [,39]          [,40]          [,41]          [,42]         
## countNA &quot;gyros_belt_z&quot; &quot;accel_belt_x&quot; &quot;accel_belt_y&quot; &quot;accel_belt_z&quot;
##         &quot;0&quot;            &quot;0&quot;            &quot;0&quot;            &quot;0&quot;           
##         [,43]           [,44]           [,45]           [,46]     
## countNA &quot;magnet_belt_x&quot; &quot;magnet_belt_y&quot; &quot;magnet_belt_z&quot; &quot;roll_arm&quot;
##         &quot;0&quot;             &quot;0&quot;             &quot;0&quot;             &quot;0&quot;       
##         [,47]       [,48]     [,49]             [,50]          
## countNA &quot;pitch_arm&quot; &quot;yaw_arm&quot; &quot;total_accel_arm&quot; &quot;var_accel_arm&quot;
##         &quot;0&quot;         &quot;0&quot;       &quot;0&quot;               &quot;19216&quot;        
##         [,51]          [,52]             [,53]          [,54]          
## countNA &quot;avg_roll_arm&quot; &quot;stddev_roll_arm&quot; &quot;var_roll_arm&quot; &quot;avg_pitch_arm&quot;
##         &quot;19216&quot;        &quot;19216&quot;           &quot;19216&quot;        &quot;19216&quot;        
##         [,55]              [,56]           [,57]         [,58]           
## countNA &quot;stddev_pitch_arm&quot; &quot;var_pitch_arm&quot; &quot;avg_yaw_arm&quot; &quot;stddev_yaw_arm&quot;
##         &quot;19216&quot;            &quot;19216&quot;         &quot;19216&quot;       &quot;19216&quot;         
##         [,59]         [,60]         [,61]         [,62]        
## countNA &quot;var_yaw_arm&quot; &quot;gyros_arm_x&quot; &quot;gyros_arm_y&quot; &quot;gyros_arm_z&quot;
##         &quot;19216&quot;       &quot;0&quot;           &quot;0&quot;           &quot;0&quot;          
##         [,63]         [,64]         [,65]         [,66]         
## countNA &quot;accel_arm_x&quot; &quot;accel_arm_y&quot; &quot;accel_arm_z&quot; &quot;magnet_arm_x&quot;
##         &quot;0&quot;           &quot;0&quot;           &quot;0&quot;           &quot;0&quot;           
##         [,67]          [,68]          [,69]              
## countNA &quot;magnet_arm_y&quot; &quot;magnet_arm_z&quot; &quot;kurtosis_roll_arm&quot;
##         &quot;0&quot;            &quot;0&quot;            &quot;19216&quot;            
##         [,70]                [,71]              [,72]              
## countNA &quot;kurtosis_picth_arm&quot; &quot;kurtosis_yaw_arm&quot; &quot;skewness_roll_arm&quot;
##         &quot;19216&quot;              &quot;19216&quot;            &quot;19216&quot;            
##         [,73]                [,74]              [,75]         
## countNA &quot;skewness_pitch_arm&quot; &quot;skewness_yaw_arm&quot; &quot;max_roll_arm&quot;
##         &quot;19216&quot;              &quot;19216&quot;            &quot;19216&quot;       
##         [,76]           [,77]         [,78]          [,79]          
## countNA &quot;max_picth_arm&quot; &quot;max_yaw_arm&quot; &quot;min_roll_arm&quot; &quot;min_pitch_arm&quot;
##         &quot;19216&quot;         &quot;19216&quot;       &quot;19216&quot;        &quot;19216&quot;        
##         [,80]         [,81]                [,82]                
## countNA &quot;min_yaw_arm&quot; &quot;amplitude_roll_arm&quot; &quot;amplitude_pitch_arm&quot;
##         &quot;19216&quot;       &quot;19216&quot;              &quot;19216&quot;              
##         [,83]               [,84]           [,85]           
## countNA &quot;amplitude_yaw_arm&quot; &quot;roll_dumbbell&quot; &quot;pitch_dumbbell&quot;
##         &quot;19216&quot;             &quot;0&quot;             &quot;0&quot;             
##         [,86]          [,87]                    [,88]                    
## countNA &quot;yaw_dumbbell&quot; &quot;kurtosis_roll_dumbbell&quot; &quot;kurtosis_picth_dumbbell&quot;
##         &quot;0&quot;            &quot;19216&quot;                  &quot;19216&quot;                  
##         [,89]                   [,90]                   
## countNA &quot;kurtosis_yaw_dumbbell&quot; &quot;skewness_roll_dumbbell&quot;
##         &quot;19216&quot;                 &quot;19216&quot;                 
##         [,91]                     [,92]                  
## countNA &quot;skewness_pitch_dumbbell&quot; &quot;skewness_yaw_dumbbell&quot;
##         &quot;19216&quot;                   &quot;19216&quot;                
##         [,93]               [,94]                [,95]             
## countNA &quot;max_roll_dumbbell&quot; &quot;max_picth_dumbbell&quot; &quot;max_yaw_dumbbell&quot;
##         &quot;19216&quot;             &quot;19216&quot;              &quot;19216&quot;           
##         [,96]               [,97]                [,98]             
## countNA &quot;min_roll_dumbbell&quot; &quot;min_pitch_dumbbell&quot; &quot;min_yaw_dumbbell&quot;
##         &quot;19216&quot;             &quot;19216&quot;              &quot;19216&quot;           
##         [,99]                     [,100]                    
## countNA &quot;amplitude_roll_dumbbell&quot; &quot;amplitude_pitch_dumbbell&quot;
##         &quot;19216&quot;                   &quot;19216&quot;                   
##         [,101]                   [,102]                
## countNA &quot;amplitude_yaw_dumbbell&quot; &quot;total_accel_dumbbell&quot;
##         &quot;19216&quot;                  &quot;0&quot;                   
##         [,103]               [,104]              [,105]                
## countNA &quot;var_accel_dumbbell&quot; &quot;avg_roll_dumbbell&quot; &quot;stddev_roll_dumbbell&quot;
##         &quot;19216&quot;              &quot;19216&quot;             &quot;19216&quot;               
##         [,106]              [,107]               [,108]                 
## countNA &quot;var_roll_dumbbell&quot; &quot;avg_pitch_dumbbell&quot; &quot;stddev_pitch_dumbbell&quot;
##         &quot;19216&quot;             &quot;19216&quot;              &quot;19216&quot;                
##         [,109]               [,110]             [,111]               
## countNA &quot;var_pitch_dumbbell&quot; &quot;avg_yaw_dumbbell&quot; &quot;stddev_yaw_dumbbell&quot;
##         &quot;19216&quot;              &quot;19216&quot;            &quot;19216&quot;              
##         [,112]             [,113]             [,114]            
## countNA &quot;var_yaw_dumbbell&quot; &quot;gyros_dumbbell_x&quot; &quot;gyros_dumbbell_y&quot;
##         &quot;19216&quot;            &quot;0&quot;                &quot;0&quot;               
##         [,115]             [,116]             [,117]            
## countNA &quot;gyros_dumbbell_z&quot; &quot;accel_dumbbell_x&quot; &quot;accel_dumbbell_y&quot;
##         &quot;0&quot;                &quot;0&quot;                &quot;0&quot;               
##         [,118]             [,119]              [,120]             
## countNA &quot;accel_dumbbell_z&quot; &quot;magnet_dumbbell_x&quot; &quot;magnet_dumbbell_y&quot;
##         &quot;0&quot;                &quot;0&quot;                 &quot;0&quot;                
##         [,121]              [,122]         [,123]          [,124]       
## countNA &quot;magnet_dumbbell_z&quot; &quot;roll_forearm&quot; &quot;pitch_forearm&quot; &quot;yaw_forearm&quot;
##         &quot;0&quot;                 &quot;0&quot;            &quot;0&quot;             &quot;0&quot;          
##         [,125]                  [,126]                  
## countNA &quot;kurtosis_roll_forearm&quot; &quot;kurtosis_picth_forearm&quot;
##         &quot;19216&quot;                 &quot;19216&quot;                 
##         [,127]                 [,128]                 
## countNA &quot;kurtosis_yaw_forearm&quot; &quot;skewness_roll_forearm&quot;
##         &quot;19216&quot;                &quot;19216&quot;                
##         [,129]                   [,130]                 [,131]            
## countNA &quot;skewness_pitch_forearm&quot; &quot;skewness_yaw_forearm&quot; &quot;max_roll_forearm&quot;
##         &quot;19216&quot;                  &quot;19216&quot;                &quot;19216&quot;           
##         [,132]              [,133]            [,134]            
## countNA &quot;max_picth_forearm&quot; &quot;max_yaw_forearm&quot; &quot;min_roll_forearm&quot;
##         &quot;19216&quot;             &quot;19216&quot;           &quot;19216&quot;           
##         [,135]              [,136]            [,137]                  
## countNA &quot;min_pitch_forearm&quot; &quot;min_yaw_forearm&quot; &quot;amplitude_roll_forearm&quot;
##         &quot;19216&quot;             &quot;19216&quot;           &quot;19216&quot;                 
##         [,138]                    [,139]                 
## countNA &quot;amplitude_pitch_forearm&quot; &quot;amplitude_yaw_forearm&quot;
##         &quot;19216&quot;                   &quot;19216&quot;                
##         [,140]                [,141]              [,142]            
## countNA &quot;total_accel_forearm&quot; &quot;var_accel_forearm&quot; &quot;avg_roll_forearm&quot;
##         &quot;0&quot;                   &quot;19216&quot;             &quot;19216&quot;           
##         [,143]                [,144]             [,145]             
## countNA &quot;stddev_roll_forearm&quot; &quot;var_roll_forearm&quot; &quot;avg_pitch_forearm&quot;
##         &quot;19216&quot;               &quot;19216&quot;            &quot;19216&quot;            
##         [,146]                 [,147]              [,148]           
## countNA &quot;stddev_pitch_forearm&quot; &quot;var_pitch_forearm&quot; &quot;avg_yaw_forearm&quot;
##         &quot;19216&quot;                &quot;19216&quot;             &quot;19216&quot;          
##         [,149]               [,150]            [,151]           
## countNA &quot;stddev_yaw_forearm&quot; &quot;var_yaw_forearm&quot; &quot;gyros_forearm_x&quot;
##         &quot;19216&quot;              &quot;19216&quot;           &quot;0&quot;              
##         [,152]            [,153]            [,154]           
## countNA &quot;gyros_forearm_y&quot; &quot;gyros_forearm_z&quot; &quot;accel_forearm_x&quot;
##         &quot;0&quot;               &quot;0&quot;               &quot;0&quot;              
##         [,155]            [,156]            [,157]            
## countNA &quot;accel_forearm_y&quot; &quot;accel_forearm_z&quot; &quot;magnet_forearm_x&quot;
##         &quot;0&quot;               &quot;0&quot;               &quot;0&quot;               
##         [,158]             [,159]             [,160]  
## countNA &quot;magnet_forearm_y&quot; &quot;magnet_forearm_z&quot; &quot;classe&quot;
##         &quot;0&quot;                &quot;0&quot;                &quot;0&quot;
</code></pre>

<pre><code class="r">unique(test_countNAs[2,])
</code></pre>

<pre><code>## [1] &quot;0&quot;  &quot;20&quot;
</code></pre>

<pre><code class="r">unique(train_countNAs[2,])
</code></pre>

<pre><code>## [1] &quot;0&quot;     &quot;19216&quot;
</code></pre>

<pre><code class="r">#check if columnames of test and training data are equal (except classe and problem_id)  
test_colnames &lt;- test_countNAs[1,test_countNAs[2,] == &quot;0&quot;]
train_colnames &lt;- train_countNAs[1,train_countNAs[2,] == &quot;0&quot;]
test_colnames
</code></pre>

<pre><code>##  [1] &quot;X&quot;                    &quot;user_name&quot;            &quot;raw_timestamp_part_1&quot;
##  [4] &quot;raw_timestamp_part_2&quot; &quot;cvtd_timestamp&quot;       &quot;new_window&quot;          
##  [7] &quot;num_window&quot;           &quot;roll_belt&quot;            &quot;pitch_belt&quot;          
## [10] &quot;yaw_belt&quot;             &quot;total_accel_belt&quot;     &quot;gyros_belt_x&quot;        
## [13] &quot;gyros_belt_y&quot;         &quot;gyros_belt_z&quot;         &quot;accel_belt_x&quot;        
## [16] &quot;accel_belt_y&quot;         &quot;accel_belt_z&quot;         &quot;magnet_belt_x&quot;       
## [19] &quot;magnet_belt_y&quot;        &quot;magnet_belt_z&quot;        &quot;roll_arm&quot;            
## [22] &quot;pitch_arm&quot;            &quot;yaw_arm&quot;              &quot;total_accel_arm&quot;     
## [25] &quot;gyros_arm_x&quot;          &quot;gyros_arm_y&quot;          &quot;gyros_arm_z&quot;         
## [28] &quot;accel_arm_x&quot;          &quot;accel_arm_y&quot;          &quot;accel_arm_z&quot;         
## [31] &quot;magnet_arm_x&quot;         &quot;magnet_arm_y&quot;         &quot;magnet_arm_z&quot;        
## [34] &quot;roll_dumbbell&quot;        &quot;pitch_dumbbell&quot;       &quot;yaw_dumbbell&quot;        
## [37] &quot;total_accel_dumbbell&quot; &quot;gyros_dumbbell_x&quot;     &quot;gyros_dumbbell_y&quot;    
## [40] &quot;gyros_dumbbell_z&quot;     &quot;accel_dumbbell_x&quot;     &quot;accel_dumbbell_y&quot;    
## [43] &quot;accel_dumbbell_z&quot;     &quot;magnet_dumbbell_x&quot;    &quot;magnet_dumbbell_y&quot;   
## [46] &quot;magnet_dumbbell_z&quot;    &quot;roll_forearm&quot;         &quot;pitch_forearm&quot;       
## [49] &quot;yaw_forearm&quot;          &quot;total_accel_forearm&quot;  &quot;gyros_forearm_x&quot;     
## [52] &quot;gyros_forearm_y&quot;      &quot;gyros_forearm_z&quot;      &quot;accel_forearm_x&quot;     
## [55] &quot;accel_forearm_y&quot;      &quot;accel_forearm_z&quot;      &quot;magnet_forearm_x&quot;    
## [58] &quot;magnet_forearm_y&quot;     &quot;magnet_forearm_z&quot;     &quot;problem_id&quot;
</code></pre>

<pre><code class="r">train_colnames
</code></pre>

<pre><code>##  [1] &quot;X&quot;                    &quot;user_name&quot;            &quot;raw_timestamp_part_1&quot;
##  [4] &quot;raw_timestamp_part_2&quot; &quot;cvtd_timestamp&quot;       &quot;new_window&quot;          
##  [7] &quot;num_window&quot;           &quot;roll_belt&quot;            &quot;pitch_belt&quot;          
## [10] &quot;yaw_belt&quot;             &quot;total_accel_belt&quot;     &quot;gyros_belt_x&quot;        
## [13] &quot;gyros_belt_y&quot;         &quot;gyros_belt_z&quot;         &quot;accel_belt_x&quot;        
## [16] &quot;accel_belt_y&quot;         &quot;accel_belt_z&quot;         &quot;magnet_belt_x&quot;       
## [19] &quot;magnet_belt_y&quot;        &quot;magnet_belt_z&quot;        &quot;roll_arm&quot;            
## [22] &quot;pitch_arm&quot;            &quot;yaw_arm&quot;              &quot;total_accel_arm&quot;     
## [25] &quot;gyros_arm_x&quot;          &quot;gyros_arm_y&quot;          &quot;gyros_arm_z&quot;         
## [28] &quot;accel_arm_x&quot;          &quot;accel_arm_y&quot;          &quot;accel_arm_z&quot;         
## [31] &quot;magnet_arm_x&quot;         &quot;magnet_arm_y&quot;         &quot;magnet_arm_z&quot;        
## [34] &quot;roll_dumbbell&quot;        &quot;pitch_dumbbell&quot;       &quot;yaw_dumbbell&quot;        
## [37] &quot;total_accel_dumbbell&quot; &quot;gyros_dumbbell_x&quot;     &quot;gyros_dumbbell_y&quot;    
## [40] &quot;gyros_dumbbell_z&quot;     &quot;accel_dumbbell_x&quot;     &quot;accel_dumbbell_y&quot;    
## [43] &quot;accel_dumbbell_z&quot;     &quot;magnet_dumbbell_x&quot;    &quot;magnet_dumbbell_y&quot;   
## [46] &quot;magnet_dumbbell_z&quot;    &quot;roll_forearm&quot;         &quot;pitch_forearm&quot;       
## [49] &quot;yaw_forearm&quot;          &quot;total_accel_forearm&quot;  &quot;gyros_forearm_x&quot;     
## [52] &quot;gyros_forearm_y&quot;      &quot;gyros_forearm_z&quot;      &quot;accel_forearm_x&quot;     
## [55] &quot;accel_forearm_y&quot;      &quot;accel_forearm_z&quot;      &quot;magnet_forearm_x&quot;    
## [58] &quot;magnet_forearm_y&quot;     &quot;magnet_forearm_z&quot;     &quot;classe&quot;
</code></pre>

<pre><code class="r">all.equal(train_colnames[1:length(train_colnames)-1], test_colnames[1:length(test_colnames)-1])
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<p>There are 160 variables in the training and testing data with 19622 training data values and 20 testing data values.
Either no value of a testing data variable is NA (not available) or all 20 values of a testing data variable are NA.
Either no value of a training data variable is NA or almost all values (19216 of 19622) of a training data variable are NA.</p>

<p>Thirdly data has been cleaned.</p>

<pre><code class="r">#NA data are removed
dim(testing_set[,names(testing_set) %in% test_colnames])
</code></pre>

<pre><code>## [1] 20 60
</code></pre>

<pre><code class="r">dim(training_set[,names(training_set) %in% train_colnames])
</code></pre>

<pre><code>## [1] 19622    60
</code></pre>

<pre><code class="r">training_subset &lt;- training_set[,names(training_set) %in% train_colnames]
testing_subset &lt;- testing_set[,names(testing_set) %in% test_colnames]

#the first 7 columns are not necessary
training_subset &lt;- training_subset[,8:length(colnames(training_subset))]
testing_subset &lt;- testing_subset[,8:length(colnames(testing_subset))]
</code></pre>

<p>Lastly the prediction model has been built.</p>

<pre><code class="r">#because the dataset is too big for using random forest, we use only 20% of the dataset
set.seed(1)
ids &lt;- createDataPartition(y=training_subset$classe, p=0.2, list=FALSE)
training_small &lt;- training_subset[ids,]

#devide the large training_set into a training and a test set
set.seed(1)
inTrain &lt;- createDataPartition(y=training_small$classe, p=0.7, list=FALSE)
training_train_set &lt;- training_small[inTrain,]
testing_train_set &lt;- training_small[-inTrain,]

#train on training set with cross validation.
set.seed(1)
modFit &lt;- train(classe ~ ., method=&quot;rf&quot;, trControl=trainControl(method = &quot;cv&quot;, number = 4), data=training_train_set)
print(modFit, digits=3)
</code></pre>

<pre><code>## Random Forest 
## 
## 2751 samples
##   52 predictor
##    5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (4 fold) 
## Summary of sample sizes: 2063, 2064, 2063, 2063 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy  Kappa
##    2    0.945     0.930
##   27    0.947     0.933
##   52    0.943     0.928
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was mtry = 27.
</code></pre>

<pre><code class="r">#predict testing
predictions &lt;- predict(modFit, newdata=testing_train_set)
print(confusionMatrix(predictions, testing_train_set$classe), digits=4)
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   A   B   C   D   E
##          A 330   8   0   0   0
##          B   2 218   6   1   2
##          C   2   1 199   3   2
##          D   0   0   0 189   5
##          E   0   1   0   0 207
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9719          
##                  95% CI : (0.9608, 0.9806)
##     No Information Rate : 0.284           
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.9645          
##  Mcnemar&#39;s Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9880   0.9561   0.9707   0.9793   0.9583
## Specificity            0.9905   0.9884   0.9918   0.9949   0.9990
## Pos Pred Value         0.9763   0.9520   0.9614   0.9742   0.9952
## Neg Pred Value         0.9952   0.9894   0.9938   0.9959   0.9907
## Prevalence             0.2840   0.1939   0.1743   0.1641   0.1837
## Detection Rate         0.2806   0.1854   0.1692   0.1607   0.1760
## Detection Prevalence   0.2874   0.1947   0.1760   0.1650   0.1769
## Balanced Accuracy      0.9893   0.9723   0.9812   0.9871   0.9786
</code></pre>

<pre><code class="r">#20 testing set
print(predict(modFit, newdata=testing_subset))
</code></pre>

<pre><code>##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E
</code></pre>

<p>The accuracy of mtry = 27 has the largest value: 0.947
The out of Sample Error is the error rate on the testing data set: 1 - .9719 = 0.0281
The prediction (classe) of 20 testing set is: B A B A A E D B A A B C B A E E A B B B</p>

</body>

</html>
